"""Build PROGMEM C arrays from Fusion Pixel Font 12px monospaced BDFs — JA variant.

Emits:

- ``src/Fonts/JIS208.h`` — JIS X 0208 rows 1..47 (symbols + kana + Level 1 kanji),
  12 wide × 12 tall, 24 B per glyph. Indexed by Shift_JIS byte pair via
  ``sjis_glyph(lead, trail)``. Missing cells get zeroed glyphs.

Shares the ASC12 path with ``convert_fusion_pixel_12.py``; we deliberately do
NOT regenerate ``ASC12.h`` here so both CJK targets can share it via the
sibling header.

JIS row 1-47 covers:
  rows  1-15 — symbols (punctuation, math, brackets, currency, etc.)
  row   4    — hiragana (84 glyphs)
  row   5    — katakana (86 glyphs)
  row   6    — Greek capitals/lowercase
  row   7    — Cyrillic
  rows  9-12 — JIS-defined drawing characters (sparsely populated)
  rows 16-47 — Level 1 kanji (2965 chars, JIS sort order)

Half-width katakana (single-byte 0xA1-0xDF) is NOT included; CJK content from
Claude is overwhelmingly full-width. cjk_render falls back to '?' for those.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Optional

FONT_ROOT = Path("/tmp/fusion-pixel/extracted")
BDF_LATIN = FONT_ROOT / "fusion-pixel-12px-monospaced-latin.bdf"
BDF_JA    = FONT_ROOT / "fusion-pixel-12px-monospaced-ja.bdf"

OUT_DIR = Path("/Users/snow/claude-desktop-buddy/src/Fonts")
OUT_JIS = OUT_DIR / "JIS208.h"

GLYPH_H = 12
GBK_W = 12  # also CJK width here — full-width JIS cell
GBK_BYTES_PER_ROW = 2
GBK_BYTES_PER_GLYPH = GLYPH_H * GBK_BYTES_PER_ROW  # 24

# JIS X 0208 row range we ship. Inclusive on both ends.
ROW_START = 1
ROW_END = 47
CELLS_PER_ROW = 94
JIS_TOTAL_GLYPHS = (ROW_END - ROW_START + 1) * CELLS_PER_ROW


def parse_bdf(path: Path) -> dict[int, list[int]]:
    """{codepoint: raw glyph bytes from BITMAP rows}. Shared with the zh-CN
    extractor; kept inline so this script runs standalone."""
    out: dict[int, list[int]] = {}
    text = path.read_text(encoding="utf-8")
    for block in re.split(r"^STARTCHAR ", text, flags=re.MULTILINE)[1:]:
        end = block.find("\nENDCHAR")
        if end < 0:
            continue
        body = block[:end]
        m = re.search(r"^ENCODING\s+(-?\d+)", body, re.MULTILINE)
        if not m:
            continue
        cp = int(m.group(1))
        if cp < 0:
            continue
        bitmap_match = re.search(r"^BITMAP\s*$", body, re.MULTILINE)
        if not bitmap_match:
            continue
        hex_rows = []
        for line in body[bitmap_match.end():].splitlines():
            line = line.strip()
            if not line:
                continue
            if not re.fullmatch(r"[0-9A-Fa-f]+", line):
                break
            hex_rows.append(line)
        glyph: list[int] = []
        for row in hex_rows:
            if len(row) % 2:
                row += "0"
            for i in range(0, len(row), 2):
                glyph.append(int(row[i:i + 2], 16))
        out[cp] = glyph
    return out


def jis_to_sjis(row: int, cell: int) -> Optional[tuple[int, int]]:
    """Convert a JIS X 0208 (row, cell) cell to its Shift_JIS (lead, trail)
    byte pair, or None if out of range."""
    if row < 1 or row > 94 or cell < 1 or cell > 94:
        return None
    if row <= 62:
        lead = ((row - 1) >> 1) + 0x81
    else:
        lead = ((row - 1) >> 1) + 0xC1
    if row % 2 == 1:
        trail = cell + (0x40 if cell >= 64 else 0x3F)
    else:
        trail = cell + 0x9E
    return (lead, trail)


def jis_to_unicode(row: int, cell: int) -> Optional[str]:
    sjis = jis_to_sjis(row, cell)
    if sjis is None:
        return None
    try:
        decoded = bytes(sjis).decode("shift_jis")
    except UnicodeDecodeError:
        return None
    if len(decoded) != 1:
        return None
    return decoded


def emit_header(glyphs: list[list[int]]) -> str:
    lines = [
        "/* Auto-generated by scripts/convert_fusion_pixel_12_ja.py — do not edit. */",
        "/* Source: Fusion Pixel Font 12px monospaced (https://github.com/TakWolf/fusion-pixel-font). */",
        "/* Licensed under SIL Open Font License 1.1 — see Fonts/OFL.txt. */",
        "",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"#define JIS208_GLYPH_W {GBK_W}",
        f"#define JIS208_GLYPH_H {GLYPH_H}",
        f"#define JIS208_BYTES_PER_ROW {GBK_BYTES_PER_ROW}",
        f"#define JIS208_BYTES_PER_GLYPH {GBK_BYTES_PER_GLYPH}",
        f"#define JIS208_GLYPH_COUNT {len(glyphs)}",
        f"#define JIS208_ROW_START {ROW_START}",
        f"#define JIS208_ROW_END   {ROW_END}  /* inclusive */",
        "",
        f"const uint8_t JIS208[JIS208_GLYPH_COUNT * JIS208_BYTES_PER_GLYPH] PROGMEM = {{",
    ]
    for g_idx, g in enumerate(glyphs):
        if len(g) < GBK_BYTES_PER_GLYPH:
            g = g + [0] * (GBK_BYTES_PER_GLYPH - len(g))
        elif len(g) > GBK_BYTES_PER_GLYPH:
            g = g[:GBK_BYTES_PER_GLYPH]
        row_bytes = ",".join(f"0x{b:02X}" for b in g)
        lines.append(f"    /* {g_idx} */ {row_bytes},")
    lines.append("};")
    lines.append("")
    lines.append(
        "/* Decode a Shift_JIS byte pair to a glyph pointer, or nullptr if the\n"
        "   pair is outside JIS X 0208 rows 1..JIS208_ROW_END or otherwise invalid. */\n"
        "static inline const uint8_t* sjis_glyph(uint8_t lead, uint8_t trail) {\n"
        "  /* Lead-byte sanity. SJIS leads: 0x81..0x9F and 0xE0..0xFC. */\n"
        "  if (lead < 0x81) return nullptr;\n"
        "  if (lead > 0x9F && lead < 0xE0) return nullptr;\n"
        "  if (lead > 0xFC) return nullptr;\n"
        "  /* Trail-byte sanity: 0x40..0x7E or 0x80..0xFC. */\n"
        "  if (trail < 0x40 || trail == 0x7F || trail > 0xFC) return nullptr;\n"
        "\n"
        "  uint8_t row;\n"
        "  if (lead < 0xE0) {\n"
        "    row = ((lead - 0x81) << 1) + 1;  /* odd row of the lead pair */\n"
        "  } else {\n"
        "    row = ((lead - 0xC1) << 1) + 1;\n"
        "  }\n"
        "  uint8_t cell;\n"
        "  if (trail < 0x9F) {\n"
        "    cell = trail - ((trail >= 0x80) ? 0x40 : 0x3F);\n"
        "  } else {\n"
        "    cell = trail - 0x9E;\n"
        "    row += 1;  /* even row */\n"
        "  }\n"
        "  if (row < JIS208_ROW_START || row > JIS208_ROW_END) return nullptr;\n"
        "  if (cell < 1 || cell > 94) return nullptr;\n"
        "\n"
        "  uint32_t idx = (uint32_t)(row - JIS208_ROW_START) * 94 + (cell - 1);\n"
        "  return JIS208 + idx * JIS208_BYTES_PER_GLYPH;\n"
        "}\n"
    )
    return "\n".join(lines)


def main() -> int:
    if not BDF_LATIN.exists() or not BDF_JA.exists():
        print(f"BDF files missing — expected at {FONT_ROOT}", file=sys.stderr)
        return 1

    latin = parse_bdf(BDF_LATIN)
    ja    = parse_bdf(BDF_JA)
    print(f"parsed latin: {len(latin)} glyphs, ja: {len(ja)} glyphs")

    jis_glyphs: list[list[int]] = []
    hits = 0
    misses = 0
    holes = 0
    for row in range(ROW_START, ROW_END + 1):
        for cell in range(1, CELLS_PER_ROW + 1):
            uni = jis_to_unicode(row, cell)
            g: list[int] = []
            if uni is not None:
                cp = ord(uni)
                g = ja.get(cp) or latin.get(cp) or []
                if len(g) >= GBK_BYTES_PER_GLYPH:
                    g = g[:GBK_BYTES_PER_GLYPH]
                    hits += 1
                else:
                    g = []
                    misses += 1
            else:
                holes += 1
            if not g:
                g = [0] * GBK_BYTES_PER_GLYPH
            jis_glyphs.append(g)
    print(f"JIS lookup: hits={hits}, misses={misses}, JIS holes={holes}, total={len(jis_glyphs)}")

    OUT_JIS.write_text(emit_header(jis_glyphs))
    size_kb = len(jis_glyphs) * GBK_BYTES_PER_GLYPH / 1024.0
    print(f"wrote {OUT_JIS}: {len(jis_glyphs)} glyphs × {GBK_BYTES_PER_GLYPH} B = {size_kb:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
