#ifdef CC_BUDDY_CJK_DISPLAY

#include "cjk_render.h"
// TFT_eSprite is exposed via M5StickCPlus.h (which pulls in the bundled
// TFT_eSPI library); we don't have a direct lib_deps entry for TFT_eSPI.
#include <M5StickCPlus.h>
#include "Fonts/ASC16.h"        // 8x16 ASCII, ships in M5StickCPlus library
#include "Fonts/GB2312_L1.h"    // 16x16 zh-CN Level 1, generated by scripts/extract_gb2312_l1.py

// Width/height per glyph family. Two width buckets keep cursor math simple
// (ASCII chars take half a CJK slot horizontally; both lines share the same
// 16 px row height so we don't need per-char baseline adjustments).
static const int ASC_W = 8;
static const int GBK_W = 16;
static const int GLYPH_H = 16;

// True iff the two bytes starting at `p` form a valid GBK pair (both in
// 0xA1..0xFE). GB2312 Level 1 hanzi all live in that range; symbols and
// pinyin in zones 1-9 too, but we ship only zones 16-55 so anything else
// falls through to the '?' replacement below.
static inline bool isGbkLead(const uint8_t* p) {
  const uint8_t b1 = p[0], b2 = p[1];
  return b1 >= 0xA1 && b1 <= 0xFE && b2 >= 0xA1 && b2 <= 0xFE;
}

// Blit a bitmap glyph onto the sprite. `glyph` is row-major: rows of
// `bytes_per_row` bytes each, MSB-first within each byte. Bits outside the
// glyph's visible width are ignored. Pixels outside the sprite are clipped
// silently by TFT_eSprite::drawPixel.
static void blitGlyph(TFT_eSprite* spr, const uint8_t* glyph,
                      int x, int y,
                      int w_px, int h_px, int bytes_per_row,
                      uint16_t color, uint16_t bgcolor) {
  const bool fillBg = (color != bgcolor);
  for (int row = 0; row < h_px; row++) {
    for (int b = 0; b < bytes_per_row; b++) {
      const uint8_t bits = pgm_read_byte(glyph + row * bytes_per_row + b);
      uint8_t mask = 0x80;
      for (int bit = 0; bit < 8; bit++) {
        const int col = b * 8 + bit;
        if (col >= w_px) break;
        const bool on = (bits & mask) != 0;
        if (on) {
          spr->drawPixel(x + col, y + row, color);
        } else if (fillBg) {
          spr->drawPixel(x + col, y + row, bgcolor);
        }
        mask >>= 1;
      }
    }
  }
}

static void drawAsc16(TFT_eSprite* spr, uint8_t c, int x, int y,
                      uint16_t color, uint16_t bgcolor) {
  // ASC16 indexes 0..255 directly; each glyph is 16 rows of 1 byte.
  const uint8_t* glyph = ASC16 + (uint32_t)c * 16;
  blitGlyph(spr, glyph, x, y, ASC_W, GLYPH_H, /*bytes_per_row=*/1, color, bgcolor);
}

static void drawGb2312(TFT_eSprite* spr, uint8_t b1, uint8_t b2, int x, int y,
                       uint16_t color, uint16_t bgcolor) {
  const uint8_t* glyph = gb2312_l1_glyph(b1, b2);
  if (glyph == nullptr) {
    // Outside Level 1 (symbols, Level 2 hanzi, or invalid pair) — render
    // two question marks side by side to flag the gap without leaving an
    // empty slot.
    drawAsc16(spr, '?', x,           y, color, bgcolor);
    drawAsc16(spr, '?', x + ASC_W,   y, color, bgcolor);
    return;
  }
  blitGlyph(spr, glyph, x, y, GBK_W, GLYPH_H, /*bytes_per_row=*/2, color, bgcolor);
}

void cjkDrawMixed(TFT_eSprite* spr, const char* text, int x, int y,
                  uint16_t color, uint16_t bgcolor) {
  if (spr == nullptr || text == nullptr) return;
  // Stop rendering once the next glyph wouldn't fit horizontally. Without
  // this guard, drawPixel calls keep going off the right edge and the text
  // looks like it's running off-screen even though only the visible
  // portion is fed to the LCD.
  const int max_right = spr->width();
  const uint8_t* p = reinterpret_cast<const uint8_t*>(text);
  int cx = x;
  while (*p) {
    int glyph_w;
    int advance;
    bool is_gbk = isGbkLead(p);
    if (is_gbk) {
      glyph_w = GBK_W;
      advance = 2;
    } else if (*p == '\n' || *p == '\r') {
      // Newlines are layout decisions for the caller — ignore inline.
      p++;
      continue;
    } else {
      glyph_w = ASC_W;
      advance = 1;
    }
    if (cx + glyph_w > max_right) break;   // would overflow — stop cleanly.
    if (is_gbk) drawGb2312(spr, p[0], p[1], cx, y, color, bgcolor);
    else        drawAsc16(spr, *p, cx, y, color, bgcolor);
    cx += glyph_w;
    p  += advance;
  }
}

int cjkMeasureMixed(const char* text) {
  if (text == nullptr) return 0;
  const uint8_t* p = reinterpret_cast<const uint8_t*>(text);
  int w = 0;
  while (*p) {
    if (isGbkLead(p)) { w += GBK_W; p += 2; }
    else if (*p == '\n' || *p == '\r') { p++; }
    else { w += ASC_W; p += 1; }
  }
  return w;
}

#endif // CC_BUDDY_CJK_DISPLAY
